server:
  port: 7080
logging:
  pattern:
    console: '%red(%d{yyyy-MM-dd HH:mm:ss.SSS}) %green([%thread]) %highlight(%-5level) %boldMagenta(%logger{10}.%M [%line]) - %cyan(%msg%n)'
  charset:
    console: UTF-8
  level:
    root: info
    cn:
      cruder: debug
# feign配置
services:
  url:
    producer: http://producer
# 自定义ribbon配置(可以单独移出去)
ribbon-map-config:
  ribbon-infos:
    #第1个值 producer为key
    producer:
        - localhost:7070
        - localhost:7071